// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWmpE0CxCF1y_9kPGit67QQLO2ver-o4',
    appId: '1:431003003636:web:295e0f4a95ac9d772e4ca1',
    messagingSenderId: '431003003636',
    projectId: 'login-flutter-b4b1e',
    authDomain: 'login-flutter-b4b1e.firebaseapp.com',
    storageBucket: 'login-flutter-b4b1e.appspot.com',
    measurementId: 'G-4FWZSDR52H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB257bYY34hn0Z6V6dpB6L_qY4jKwdyiAM',
    appId: '1:431003003636:android:9ce1576260e7d73d2e4ca1',
    messagingSenderId: '431003003636',
    projectId: 'login-flutter-b4b1e',
    storageBucket: 'login-flutter-b4b1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJl8nCgLxgTunhpWMdH5SP70NelyChrk',
    appId: '1:431003003636:ios:94f86e6dbc51cc2e2e4ca1',
    messagingSenderId: '431003003636',
    projectId: 'login-flutter-b4b1e',
    storageBucket: 'login-flutter-b4b1e.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJl8nCgLxgTunhpWMdH5SP70NelyChrk',
    appId: '1:431003003636:ios:c49cf7751ad8a67c2e4ca1',
    messagingSenderId: '431003003636',
    projectId: 'login-flutter-b4b1e',
    storageBucket: 'login-flutter-b4b1e.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
